version: '2.3'
services:

  webrtc-webrtc-dev:
    build:
      context: docker
      dockerfile: Dockerfile
    container_name: webrtc-webrtc-dev
    working_dir: /application
    #    command: bash -c "cd /application/data && mkdir -p {history,hls,logs,record,thumbs} && chmod a+rwx history hls logs record thumbs && /opt/nginx/sbin/nginx"
    #    command: bash -c "tail -f /dev/null"
    restart: always
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - WS_PORT=8083
      - RTMP_DST=rtmp://127.0.0.1:1939
#    command: /bin/bash -c "env GODEBUG=cgocheck=0 go run main.go"
    volumes:
      - ./src:/application/:rw
    network_mode: host
